name: mypocket
description: "A Unified Digital Wallet."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  animated_notch_bottom_bar: ^1.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  carousel_slider: 5.0.0
  cloud_firestore: ^5.6.5
  cloud_firestore_platform_interface: ^6.6.5
  cloud_firestore_web: ^4.4.5
  collection: ^1.19.1
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_auth_platform_interface: ^7.6.1
  firebase_auth_web: ^5.14.1
  firebase_core: ^3.12.1
  firebase_core_platform_interface: ^5.4.0
  firebase_core_web: ^2.21.1
  firebase_performance: ^0.10.1+4
  firebase_performance_platform_interface: ^0.1.5+4
  firebase_performance_web: ^0.1.7+10
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  flutter_svg: ^2.0.17
  flutter_facebook_auth: ^7.1.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  google_sign_in_android: ^6.2.0
  google_sign_in_ios: ^5.8.1
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  googleapis: ^14.0.0
  http: ^1.0.0
  intl: 0.19.0
  json_path: ^0.7.5
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.16
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.4
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  shared_preferences_android: ^2.4.8
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^6.1.4
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: ^2.1.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  stream_transform: ^2.1.1
  share_plus: ^10.1.4
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.15
  url_launcher_ios: ^6.3.2
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.0
  url_launcher_windows: ^3.1.4 



dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
  - assets/MyWalletLogo.png
  - assets/MyPocketBrand.png
  - assets/google_logo.svg
  - assets/facebook_logo.svg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
