// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5sWpyPXyU67NSGcHCqeothsKcIPDXsD0',
    appId: '1:128150028593:web:3bcbb5e045ceb28ddf3010',
    messagingSenderId: '128150028593',
    projectId: 'my-pocket-fc2b6',
    authDomain: 'my-pocket-fc2b6.firebaseapp.com',
    databaseURL: 'https://my-pocket-fc2b6-default-rtdb.firebaseio.com',
    storageBucket: 'my-pocket-fc2b6.firebasestorage.app',
    measurementId: 'G-WGCQP38Y65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwyJqTmvxlOI2D0q9tsZmH9Cv8M8KJko',
    appId: '1:128150028593:android:ee96508fe1923808df3010',
    messagingSenderId: '128150028593',
    projectId: 'my-pocket-fc2b6',
    databaseURL: 'https://my-pocket-fc2b6-default-rtdb.firebaseio.com',
    storageBucket: 'my-pocket-fc2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLPoHG6epf7VS9H0E0H1hVuvHCL9PmE1Y',
    appId: '1:128150028593:ios:3a6e672e426d840adf3010',
    messagingSenderId: '128150028593',
    projectId: 'my-pocket-fc2b6',
    databaseURL: 'https://my-pocket-fc2b6-default-rtdb.firebaseio.com',
    storageBucket: 'my-pocket-fc2b6.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLPoHG6epf7VS9H0E0H1hVuvHCL9PmE1Y',
    appId: '1:128150028593:ios:3a6e672e426d840adf3010',
    messagingSenderId: '128150028593',
    projectId: 'my-pocket-fc2b6',
    databaseURL: 'https://my-pocket-fc2b6-default-rtdb.firebaseio.com',
    storageBucket: 'my-pocket-fc2b6.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5sWpyPXyU67NSGcHCqeothsKcIPDXsD0',
    appId: '1:128150028593:web:4b605e8eb0e9ecdddf3010',
    messagingSenderId: '128150028593',
    projectId: 'my-pocket-fc2b6',
    authDomain: 'my-pocket-fc2b6.firebaseapp.com',
    databaseURL: 'https://my-pocket-fc2b6-default-rtdb.firebaseio.com',
    storageBucket: 'my-pocket-fc2b6.firebasestorage.app',
    measurementId: 'G-9XY66R1WPW',
  );
}
